spring:
  datasource:
    url: jdbc:mysql://localhost/gaia
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  aop:
    auto: true
    proxy-target-class: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy

flyway:
  enabled: true
  out-of-order: true
  encoding: UTF-8

gaia:
  jersey:
    access_control_allow_origin: \*

  redis:
    host: localhost

  jms:
    url: tcp://localhost:61616
    username: gaia
    password: gaia

  auth:
    admin_token_expire_minutes: 30
    allow_public_access: true

server:
  port: 8080
  context-path: /gaia/rest

---
spring:
    profiles: test
    datasource:
          url: jdbc:h2:mem:gaia;DB_CLOSE_DELAY=-1;MODE=MySQL;INIT=RUNSCRIPT FROM 'classpath:init_test_db.sql';
          username: sa
          password:
          driver-class-name: org.h2.Driver

---
spring:
    profiles: production
